default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

production:
  <<: *default
  database: etyme_prod

development:
  <<: *default
  database: etyme_development
